Start to Refactor CassandraStorage
thelastpickle/cassandra-reaper pull request #1294
Opened 2023-05-05 03:23 UTC by Miles-Garnsey

This PR begins the refactoring process on CassandraStorage as discussed in #1265. The long term goals are:

1. Split up the monolithic IStorage,  IDistributedStorage interfaces and monolithic CassandraStorage and MemoryStorage classes so that we end up with smaller DAO classes mapping more closely to the types defined in `core`.
2. Ensure return types are aligned with types from `core` where possible and are never `ResultSet`s (which are almost untyped and hard to work with).
3. Bring the codebase into a more manageable state where it is clear which types are collaborating with other types.

This PR is a very small step in that direction, and simply delegates many of the storage operations from CassandraStorage to DAO types. 

Further steps need to be taken to reflect the broad cuts made here in the interfaces and in MemoryStorage, before creating smaller interfaces that the new DAO types adhere to and passing those interfaces (instead of e.g. the larger monolithic IStorage)  to consumers.

2023-05-09 09:47 UTC, adejanovski requested changes
Couple of requested changes to unblock testing.

2023-05-09 09:47 UTC, adejanovski commented on src/server/src/main/java/io/cassandrareaper/storage/cassandra/CassandraStorage.java
> +    }
```suggestion
    version = cassandra.getMetadata().getAllHosts()
        .stream()
        .map(h -> h.getCassandraVersion())
        .min(VersionNumber::compareTo)
        .get();

    boolean skipMigration = System.getenv().containsKey("REAPER_SKIP_SCHEMA_MIGRATION")
        ? Boolean.parseBoolean(System.getenv("REAPER_SKIP_SCHEMA_MIGRATION"))
        : Boolean.FALSE;

    if (skipMigration) {
      LOG.info("Skipping schema migration as requested.");
    } else {
      MigrationManager.initializeAndUpgradeSchema(cassandra, session, config, version, mode);
    }

    this.eventsDao =  new EventsDao(session);
    this.metricsDao  = new MetricsDao(session);
    this.snapshotDao = new SnapshotDao(session);
    this.operationsDao  = new OperationsDao(session);
    this.concurrency = new Concurrency(version, reaperInstanceId, session);
    this.repairUnitDao  = new RepairUnitDao(defaultTimeout, session);
    this.repairSegmentDao = new RepairSegmentDao(concurrency, repairUnitDao, session);
    this.repairScheduleDao = new RepairScheduleDao(repairUnitDao, session);
    this.clusterDao  = new ClusterDao(repairScheduleDao, repairUnitDao, eventsDao, session, objectMapper);
    this.repairRunDao =  new RepairRunDao(repairUnitDao, clusterDao, repairSegmentDao, session);
```

Schema migrations need to happen before creating the DAOs. It looks like their constructors invoke `prepareStatements()` which will do exactly that but on non existing tables.

After moving this block I was able to start Reaper properly.

2023-05-09 09:47 UTC, adejanovski commented on src/server/src/main/java/io/cassandrareaper/storage/cassandra/RepairScheduleDao.java
> +    this.session = session;
```suggestion
    this.session = session;
    prepareStatements()
```

2023-05-10 04:50 UTC, Miles-Garnsey commented
@adejanovski thanks for the input, the tests now pass. Can you please complete your review, and especially take a look at what I've done with the acceptance tests? I've removed all references to Cassandra 2.x to get things running, but maybe we can leave the cases where the cluster to be repaired is Cassandra 2.x, as long as the backend is 3.x+?

I do note that the tests against trunk all seem to be failing, I'm not sure if that is a problem or not given that trunk is presumably often  unstable (or API incompatible with Reaper perhaps? Not sure...)

2023-05-10 07:57 UTC, adejanovski submitted a review, later dismissed
Very nice refactorings!
There are some of the tests in the memory jobs that need to be re-introduced and a few comments that should be deleted.
Otherwise LGTM.
You can merge the PR once the above points have been addressed and CI passes.

2023-05-10 07:57 UTC, adejanovski commented on .github/workflows/ci.yaml
> +        cassandra-version: ['binary:3.0.25', 'binary:3.11.11', 'binary:4.0.1', 'github:apache/trunk']
You'll need to reintroduce the removed entries from the matrix.
This job uses the memory backend and only tests repairs on such versions.

2023-05-10 07:57 UTC, adejanovski commented on src/server/src/main/java/io/cassandrareaper/storage/cassandra/CassandraStorage.java
> +    // Compute the hourly buckets since the requested lower bound timestamp
This comment can be removed.

2023-05-10 07:57 UTC, adejanovski commented on src/server/src/main/java/io/cassandrareaper/storage/cassandra/CassandraStorage.java
> +    // Grab repair runs asynchronously for all the ids returned by the index table
These comments should be removed/moved to the DAO.

2023-05-10 07:57 UTC, adejanovski commented on src/server/src/main/java/io/cassandrareaper/storage/cassandra/CassandraStorage.java
> +    // Defuture the repair_run rows and build the strongly typed RepairRun objects from the contents.
These comments should be removed/moved to the DAO.

2023-05-10 07:57 UTC, adejanovski commented on src/server/src/main/java/io/cassandrareaper/storage/cassandra/CassandraStorage.java
> +    // Grab repair runs asynchronously for all the ids returned by the index table
These comment should be removed/moved to the DAO.

2023-05-10 07:57 UTC, adejanovski commented on src/server/src/main/java/io/cassandrareaper/storage/cassandra/CassandraStorage.java
> +    // assert we're not overwriting a cluster with the same name but different node list
This comment should be removed/moved to the DAO.

2023-05-10 07:57 UTC, adejanovski commented on src/server/src/main/java/io/cassandrareaper/storage/cassandra/CassandraStorage.java
> +    // Compute the ten minutes buckets since the requested lower bound timestamp
This comment should be removed/moved to the DAO.

2023-05-11 01:08 UTC, Miles-Garnsey commented
All changes made as requested, with removal of `dateOf` references to ensure compatibility with `trunk`. I'll merge once/if tests pass.

2023-05-16 14:39 UTC, adejanovski approved these changes

2023-05-16 14:39 UTC, merged