Make UUIDs returned from PostgresStorage deterministic to reduce confusion
thelastpickle/cassandra-reaper pull request #131
Opened 2017-07-03 14:33 UTC by Bj0rnen

I'm not sure if there was a particular reason that that least significant 64 bits were taken from a time-based UUID. It led to surprising behavior, like all of the UUIDs (returned from various endpoints) changing every time Reaper got restarted.

Perhaps `toSequenceId` should also require the least significant 64 bits to be 0, so that only the reported UUID can be used for commands like spreaper's pause-schedule.

2017-07-03 15:48 UTC, Bj0rnen commented
Didn't actually fix it, because there are multiple other places that do the same thing. I will factor them out.

2017-07-03 21:17 UTC, michaelsembwever commented
Thanks for seeing and fixing this @Bj0rnen 
Went straight past me. Of course, over multiple jvm processes we need UUIDs to be reproducible from timestamp (within the storage implementation)…

2017-07-03 21:18 UTC, michaelsembwever commented
@Bj0rnen is this ready for review now?

2017-07-04 07:10 UTC, michaelsembwever requested changes

2017-07-04 07:10 UTC, michaelsembwever commented on src/main/java/com/spotify/reaper/storage/PostgresStorage.java
> +  public static UUID fromSequenceId(long insertedId) {
The problem with re-using these static methods is it creates a cyclic dependency between the `com.spotify.reaper.storage` and `com.spotify.reaper.storage.postgresql` packages.

If the two methods are moved something into the `com.spotify.reaper.storage.postgresql` package then the dependency direction remains only from `com.spotify.reaper.storage` to `com.spotify.reaper.storage.postgresql` as it is today.

2017-07-04 09:13 UTC, Bj0rnen commented on src/main/java/com/spotify/reaper/storage/PostgresStorage.java
> +  public static UUID fromSequenceId(long insertedId) {
Good point! I'll split those to a separate class.

2017-07-04 10:23 UTC, michaelsembwever approved these changes

2017-07-04 12:51 UTC, michaelsembwever commented
Pushed branch to https://github.com/thelastpickle/cassandra-reaper/tree/DeterministicPostgresUUID
 and made a few small edits.

From there it was merged to master.

2017-07-04 12:51 UTC, closed without merging