Upgrade dropwizard.version to 2.1.0
thelastpickle/cassandra-reaper pull request #1481
Opened 2024-03-18 23:47 UTC by FieteO

Bump `dropwizard.version` to `2.1.0`. Fixes #1462

2024-03-19 09:09 UTC, FieteO commented
@adejanovski It looks like the setup of the tmate session is timing out. Is this related to my changes, or some flakiness in the Actions workflow?

2024-03-19 09:17 UTC, adejanovski commented
> @adejanovski It looks like the setup of the tmate session is timing out. Is this related to my changes, or some flakiness in the Actions workflow?

tmate stays open for 30 minutes and then times out to allow the workflow to end.
Nothing misbehaving here, the core issue is in the breakage that the dropwizard upgrade created.

2024-03-19 10:26 UTC, FieteO commented
Ah, I didn't see the failing test step before. Is there any way of running these (integration?) tests locally?
I tried to invoke `TEST_TYPE=ccm ./.github/scripts/run-tests.sh` but that fails with not finding the `ccm` executable.
I guess I could install that, but it would likely still fail right?

2024-03-21 22:59 UTC, FieteO commented
`2.1.0` seems to work now. Shall I try to bump it to [the last patch version](https://mvnrepository.com/artifact/io.dropwizard/dropwizard-core) `2.1.12` @adejanovski ?

2024-03-22 09:19 UTC, adejanovski commented
> `2.1.0` seems to work now. Shall I try to bump it to [the last patch version](https://mvnrepository.com/artifact/io.dropwizard/dropwizard-core) `2.1.12` @adejanovski ?

That seems like a good idea. Thanks for handling this @FieteO !

2024-03-22 13:45 UTC, adejanovski requested changes
Looking good :+1: 

Just one leftover comment to remove and we're good to go.

2024-03-22 13:45 UTC, adejanovski commented on src/server/src/main/java/io/cassandrareaper/management/ClusterFacade.java
> +      // ObjectMapper mapper = Jackson.newObjectMapper();
**nit:** could you remove this comment?

2024-03-22 16:41 UTC, FieteO commented on src/server/src/main/java/io/cassandrareaper/management/ClusterFacade.java
> +      // ObjectMapper mapper = Jackson.newObjectMapper();
Done

2024-03-23 15:23 UTC, adejanovski approved these changes
Awesome! Thanks @FieteO 🙏

2024-03-23 15:23 UTC, merged