cassandra fix table properties
thelastpickle/cassandra-reaper pull request #257
Opened 2017-10-30 07:16 UTC by michaelsembwever

Previous attempt in `002_table_properties.cql` overwrote and disabled the key cache setting.

This restores key cache to be enabled on every table.

It also completely disables `dclocal_read_repair`, which has no purpose for reaper.

2017-10-30 10:01 UTC, adejanovski commented on src/server/src/main/resources/db/cassandra/009_table_properties.cql
> +  WITH caching = {'keys':'NONE', 'rows_per_partition':'10'}
Why still `NONE` for key cache here ?

2017-10-30 10:47 UTC, michaelsembwever commented on src/server/src/main/resources/db/cassandra/009_table_properties.cql
> +  WITH caching = {'keys':'NONE', 'rows_per_partition':'10'}
thanks for catching that!

2017-10-31 17:17 UTC, adejanovski requested changes
This PR now conflicts with #261 which has just been merged. They both use the same version number for schema migration.

Here it should be bumped up to `010_` instead of `009_`.

2017-10-31 20:02 UTC, michaelsembwever commented
> Here it should be bumped up to 010_ instead of 009_.

Yes, i'm on it. Presuming i'm free to merge otherwise.

2017-10-31 20:25 UTC, adejanovski commented
you are :)

2017-10-31 21:28 UTC, merged