WIP – Bash completion for spreaper
thelastpickle/cassandra-reaper pull request #359
Opened 2018-03-05 09:33 UTC by michaelsembwever

todo
 - still need to test that it gets installed onto machines correctly…

2018-03-06 05:35 UTC, michaelsembwever commented
@joaquincasares are you any good at knowing how, and testing, that the bash completion script gets installed into the correct location during binary install.

2018-03-06 21:26 UTC, joaquincasares commented
@michaelsembwever what gets outputted here is pretty bad, but it works for basic use cases.

https://github.com/joaquincasares/python-bashcomplete

I remember it being slightly buggy in complicated use cases, but the outputted file should be enough to get you up and running. Once you try to customize it you'll quickly realize where the shortfalls are.

Sadly, all I know is what I programmed into this repo and that was after quite a bit of time trying to learn it all. The syntax is what killed me the most! :p 

I just now realized you already had a commit and that looks far better than what my code generates! As far as testing, try: `. ./path/to/completion-file`.

Upon install, I believe this is the ideal place: `/etc/bash_completion`.

Source: https://www.howtoforge.com/how-to-add-bash-completion-in-debian

2018-03-06 22:09 UTC, michaelsembwever commented
@joaquincasares 
> I just now realized you already had a commit and that looks far better than what my code generates! …
> Upon install, I believe this is the ideal place: /etc/bash_completion.
> Source: https://www.howtoforge.com/how-to-add-bash-completion-in-debian

Yeah, I wrote that by hand, and it looks up autocompletion by making itself `spreaper` calls. 
So the remaining piece is just ensuring that the script gets put into `/etc/bash_completion.d/`
And when that doesn't work, asking the user to put the line `. /etc/bash_completion.d/spreaper` into their bash profile.

2018-03-06 22:59 UTC, joaquincasares commented
Oh, good catch. Yup, `/etc/bash_completion.d/` would be preferred. And that's a good note if they modified their profile for whatever reason.

Your code looks great though! As best as I can tell. :)

2018-03-10 00:46 UTC, michaelsembwever commented
@internetstaff have any input on this PR?

2018-03-11 01:22 UTC, internetstaff commented
lgtm from an rhel packaging perspective, but I can't test it yet

Thanks for knocking this out - it was on my wishlist / todo!

2018-03-13 18:04 UTC, adejanovski requested changes
I've tested the package on Ubuntu after fixing the Makefile and completion works as expected there.

Great addition!

2018-03-14 01:31 UTC, michaelsembwever commented on src/packaging/Makefile
> +	cp etc/bash_completion.d/spreaper build/etc/bash_completion.d/
fixed. thanks. ps don't we have any tests for this?

2018-03-14 20:37 UTC, adejanovski approved these changes

2018-03-14 23:25 UTC, closed without merging