Improve start time selection for schedules
thelastpickle/cassandra-reaper pull request #442
Opened 2018-06-11 17:33 UTC by adejanovski

Fixes #398 
Fixes #241 

This commit eases using the UI to create repair schedules by adjusting the time from the client timezone to UTC (as the server uses UTC).
It also allows activation times in the past, which will trigger a repair immediately.
A "run now" button was added to the UI in order to start a schedule right away by updating the next activation time.

2018-06-16 00:38 UTC, michaelsembwever commented
This introduces two features. Why wasn't it submitted as two separate pull requests? (At minimum two separate commits)

2018-06-16 01:01 UTC, michaelsembwever commented
>This commit eases using the UI to create repair schedules by adjusting the time from the client timezone to UTC (as the server uses UTC).

Was it considered to have clients send timestamps in UTC (opposed to having the server translate timestamps back to UTC).
The clients here are limited: `spreaper` and the UI.

The way `RepairScheduleResource.adjustTimeDifferenceOnNextActivation(..)` works with a delta in milliseconds makes me a bit uneasy. It's a bit of a hack in lei of proper timezone handling (or enforcing).

For example if it's possible to enforce clients to do timestamps in UTC it would be simpler approach because it
 - avoids adding the `clientTime` parameter everywhere,
 - avoids adding the `adjustTimeDifferenceOnNextActivation(..)` method,
 - makes more sense as `spreaper` already documents that the `--schedule-trigger-time` is expected in UTC format,
 - not have to figure out if the trigger time argument was specified by the client in its local TZ or intentionally in UTC (as documented).

Maybe this stuff was considered?

2018-06-16 01:19 UTC, michaelsembwever requested changes

2018-06-16 01:19 UTC, michaelsembwever commented on src/server/src/main/java/io/cassandrareaper/resources/RepairScheduleResource.java
> +      adjustedNextActivation = adjustedNextActivation.plusMillis(timeDifference.intValue());
Isn't this making the presumption that the client is sending in the nextActiviation dateTime in its local timezone format?

The API requests that the `scheduleTriggerTime` argument be in UTC, ref https://github.com/thelastpickle/cassandra-reaper/blob/master/src/packaging/bin/spreaper#L236

Now if the client follows the API it breaks.

2018-06-16 01:19 UTC, michaelsembwever commented on src/server/src/main/java/io/cassandrareaper/resources/RepairScheduleResource.java
>        nextActivation = DateTime.now().plusDays(1).withTimeAtStartOfDay();
i think this line deserves a comment, referencing that it's forced to UTC from https://github.com/thelastpickle/cassandra-reaper/blob/master/src/server/src/main/java/io/cassandrareaper/ReaperApplication.java#L142


Although that line in ReaperApplication really needs to be replaced with 
```
    TimeZone.setDefault(TimeZone.getTimeZone("UTC"));
    DateTimeZone.setDefault(DateTimeZone.UTC);```

2018-06-16 01:22 UTC, michaelsembwever commented on src/server/src/main/java/io/cassandrareaper/resources/RepairScheduleResource.java
>        nextActivation = DateTime.now().plusDays(1).withTimeAtStartOfDay();
I would also look at improving that line of code as well
```
nextActivation = DateTime.now().plusDays(1).withTimeAtStartOfDay();
```

What we want is midnight local time, not midnight UTC. 
To make that possible we want need to save the original timezone in `ReaperApplication` before forcing it to UTC. The original saved timezone could then be made available via `AppContext`.

2018-06-28 18:48 UTC, adejanovski commented
I've squashed and pushed my latest changes. Should be all good now @michaelsembwever .

2018-06-29 10:25 UTC, michaelsembwever submitted a review, later dismissed

2018-07-03 17:05 UTC, adejanovski commented on src/server/src/main/java/io/cassandrareaper/resources/RepairScheduleResource.java
> +      context.storage.updateRepairSchedule(newSchedule);
As discussed together, the schedule can already shift if Reaper misses the launch window or if the repair lasts for longer than necessary to match the activation time.
I agree we may want to come up with something more predictable in the future though.

2018-07-03 19:27 UTC, merged