Fix RepairRun timestamps, honouring different run states.
thelastpickle/cassandra-reaper pull request #651
Opened 2019-04-24 05:55 UTC by michaelsembwever

ref:
 - https://github.com/thelastpickle/cassandra-reaper/issues/603

2019-04-24 17:34 UTC, SesquipedalianDefenestrator commented on src/server/src/main/java/io/cassandrareaper/storage/cassandra/Migration008.java
> +   *  delegates to Migration009 as that does everything already.
```suggestion
   *  delegates to FixRepairSegmentTimestamps as that does everything already.
```

2019-04-24 17:36 UTC, SesquipedalianDefenestrator commented on src/server/src/main/java/io/cassandrareaper/storage/cassandra/Migration011.java
>     *  delegates to Migration009 as that does everything already.
```suggestion
   *  delegates to FixRepairSegmentTimestamps as that does everything already.
```

2019-04-24 17:37 UTC, SesquipedalianDefenestrator commented on src/server/src/main/java/io/cassandrareaper/storage/cassandra/Migration012.java
>     *  delegates to Migration009 as that does everything already.
```suggestion
   *  delegates to FixRepairSegmentTimestamps as that does everything already.
```

2019-04-24 17:43 UTC, SesquipedalianDefenestrator requested changes
A few nitpicky comment updates to match the code updates

2019-04-24 18:05 UTC, SesquipedalianDefenestrator commented
For the failing test, I suspect the postgres UPDATE statements need = CAST(NULL as timestamp) or possibly = CAST(NULL as TIMESTAMP WITH TIME ZONE)

2019-04-24 18:56 UTC, SesquipedalianDefenestrator commented
The Cassandra fix logic makes sense to me, but I'm having a bit of trouble with both instances of `V12_0_0__fix_repair_run_timestamps.sql`.  I don't see where it's setting `end_date` to anything but NULL. Am I missing something?

2019-04-24 20:16 UTC, michaelsembwever commented
> The Cassandra fix logic makes sense to me, but I'm having a bit of trouble with both instances of `V12_0_0__fix_repair_run_timestamps.sql`. I don't see where it's setting `end_date` to anything but NULL. Am I missing something?

I'm not sure I follow the question.
Both sql scripts only ever set `end_date` to `NULL`.

This is to meet the precondition here:  https://github.com/thelastpickle/cassandra-reaper/pull/651/files#diff-206e460c603d749f438e724e1023f236R303

2019-04-24 22:26 UTC, SesquipedalianDefenestrator commented on src/server/src/main/resources/db/h2/V12_0_0__fix_repair_run_timestamps.sql
> +AND state = 0;
```suggestion
AND state = 'NOT_STARTED';
```

2019-04-24 22:27 UTC, SesquipedalianDefenestrator commented on src/server/src/main/resources/db/h2/V12_0_0__fix_repair_run_timestamps.sql
> +AND state != 2;
```suggestion
AND state != 'ERROR';
```

2019-04-24 22:27 UTC, SesquipedalianDefenestrator commented on src/server/src/main/resources/db/h2/V12_0_0__fix_repair_run_timestamps.sql
> +AND state != 3;
```suggestion
AND state != 'DONE';
```

2019-04-24 22:27 UTC, SesquipedalianDefenestrator commented on src/server/src/main/resources/db/h2/V12_0_0__fix_repair_run_timestamps.sql
> +AND state != 5;
```suggestion
AND state != 'ABORTED';
```

2019-04-24 22:28 UTC, SesquipedalianDefenestrator commented on src/server/src/main/resources/db/h2/V12_0_0__fix_repair_run_timestamps.sql
> +AND state != 4;
```suggestion
AND state != 'PAUSED';
```

2019-04-24 22:29 UTC, SesquipedalianDefenestrator commented on src/server/src/main/resources/db/h2/V12_0_0__fix_repair_run_timestamps.sql
> +AND state = 4;
```suggestion
AND state = 'PAUSED';
```

2019-04-24 22:30 UTC, SesquipedalianDefenestrator commented on src/server/src/main/resources/db/postgres/V12_0_0__fix_repair_run_timestamps.sql
> +AND state = 0;
```suggestion
AND state = 'NOT_STARTED';
```

2019-04-24 22:30 UTC, SesquipedalianDefenestrator commented on src/server/src/main/resources/db/postgres/V12_0_0__fix_repair_run_timestamps.sql
> +AND state != 2;
```suggestion
AND state != 'ERROR';
```

2019-04-24 22:31 UTC, SesquipedalianDefenestrator commented on src/server/src/main/resources/db/postgres/V12_0_0__fix_repair_run_timestamps.sql
> +AND state != 3;
```suggestion
AND state != 'DONE';
```

2019-04-24 22:31 UTC, SesquipedalianDefenestrator commented on src/server/src/main/resources/db/postgres/V12_0_0__fix_repair_run_timestamps.sql
> +AND state != 5;
```suggestion
AND state != 'ABORTED';
```

2019-04-24 22:31 UTC, SesquipedalianDefenestrator commented on src/server/src/main/resources/db/postgres/V12_0_0__fix_repair_run_timestamps.sql
> +AND state != 4;
```suggestion
AND state != 'PAUSED';
```

2019-04-24 22:32 UTC, SesquipedalianDefenestrator commented on src/server/src/main/resources/db/postgres/V12_0_0__fix_repair_run_timestamps.sql
> +AND state = 4;
```suggestion
AND state = 'ABORTED';
```

2019-04-24 22:33 UTC, SesquipedalianDefenestrator requested changes
Sorry, I was wrong on the cause of the type mismatch on the SQL migrations (or there's multiple).
H2 and Postgres both use a string representation for State.

2019-04-24 22:40 UTC, SesquipedalianDefenestrator commented
What I mean is, the original error that prompted this change is that RepairRun.endTime being set to null causes an error and a failure to purge old entries.  `FixRepairRunTimestamps.java` now sets endTime = startTime for ABORTED runs, which prevents that problem for the Cassandra back-end.

For H2 and Postgres backend migrations, though, I can't find an equivalent that's setting endTime = startTime for ABORTED runs.  Don't we need to do something like:
```
UPDATE repair_run
SET end_time = start_time
WHERE end_time is NULL
AND status = 'ABORTED';
```

2019-04-25 00:47 UTC, michaelsembwever commented
> What I mean is, the original error that prompted this change is that RepairRun.endTime being set to null causes an error and a failure to purge old entries. FixRepairRunTimestamps.java now sets endTime = startTime for ABORTED runs, which prevents that problem for the Cassandra back-end.

my boolean logic was whack. have replaced the exist `SELECT`  with a `WHERE state NOT IN (..)`

> For H2 and Postgres backend migrations, though, I can't find an equivalent that's setting endTime = startTime for ABORTED runs. Don't we need to do something like:

Indeed! Completely went by me. Fixed (see both `V12..cql` scripts).

2019-04-25 03:06 UTC, SesquipedalianDefenestrator approved these changes
Revamped logic makes total sense to me now.
Failed tests don't look as concerning, anyways.
One of them was a "git clone" failure, so I'll chalk that up to test infra
One of the test failures I don't understand, but smells a bit like a flaky test rather than a true failure.
The flapping reaper test looks like maybe a credential mismatch?

You're probably more familiar with the project's test infra state than I am, but the failures all look likely to be unrelated to these changes from what I can tell.

2019-04-25 03:16 UTC, michaelsembwever commented
> One of the test failures I don't understand, but smells a bit like a flaky test rather than a true failure.

Yes it looks that way!

I am taking your last comment as a reviewer `+1` , hope this is correct?
Once I get the tests passing I will merge.

2019-04-25 03:18 UTC, SesquipedalianDefenestrator commented
Yep, +1.  I thought I'd had "Approve" selected, but either I didn't or it didn't count it as a real approval because I don't have write access.

2019-04-25 03:28 UTC, michaelsembwever commented
Thanks. Yes you did approve the changes :-)

2019-04-25 03:45 UTC, merged