WIP: Documentation for Sidecar Mode
thelastpickle/cassandra-reaper pull request #707
Opened 2019-06-13 15:51 UTC by wallrj

Stacked on #622 

This is currently a brain dump of how *I* am imagining we'll use Sidecar Mode in https://github.com/sky-uk/cassandra-operator/pull/97

This is very much work-in-progress and based on my shallow understanding of how Reaper works and what it does.

Please comment, if you have time.

2019-06-14 06:50 UTC, michaelsembwever commented on src/docs/content/docs/usage/sidecar_mode.md
> + * *Fault Tolerance*: Since there is one Reaper process per node, the Reaper services will be as resilient as the parent Cassandra cluster.
Kinda… 

If the Reaper process crashes then no repairs will run on that Cassandra node. This includes all token-ranges that have a replica on that node.

2019-06-14 06:50 UTC, michaelsembwever commented
nice addition!  @adejanovski has the final review on this.

2019-06-18 19:29 UTC, adejanovski commented
That's some great documentation you've added here @wallrj.
I'll take a very close look ASAP and post my comments, but I'm very happy with how it looks already.

Thanks!

2019-07-19 06:09 UTC, adejanovski requested changes
Thanks a lot for writing this documentation.
I'll handle the update of the [multi dc architecture page](http://cassandra-reaper.io/docs/usage/multi_dc/) to add the sidecar mode.
There are a few opinionated statements in the docs that emphasize on k8s a little bit too much IMHO and the sidecar mode, while it matches this use case, wasn't specifically designed for it.

Let's revisit the PR once we have a better understanding of how the sidecar mode performs in different scenarios (multi clusters with central admin, self registering of clusters, etc...).

Thanks again, looking forward to getting this merged once we're ready.

2019-07-19 06:09 UTC, adejanovski commented on src/docs/content/docs/usage/sidecar_mode.md
> +   If you prefer to deploy a single Reaper cluster to manage multiple Cassandra clusters then Sidecar Mode may not be suitable for you.
I have to disagree here, we're still aiming at achieving federation of Reaper instances so that we can centralize repair management across the fleet.

2019-07-19 06:09 UTC, adejanovski commented on src/docs/content/docs/usage/sidecar_mode.md
> + * *Container orchestration (Kubernetes) preferred*: Following on from the "one-reaper-per-cluster" caveat (above) it is also worth noting that it is easiest to deploy Reaper in Sidecar Mode if your
Any deployment that relies on Puppet, Chef, Ansible, etc... should be able to handle this easily as well.
We didn't implement the sidecar mode with k8s nor containers in mind.

2019-07-19 06:09 UTC, adejanovski commented on src/docs/content/docs/usage/sidecar_mode.md
> +   If you are not using Kubernetes (or similar) it may be overly complicated to deploy in a secure and resilient Sidecar Mode Reaper cluster.
Again, I disagree.
What makes you think it would be overly complicated in a non containerized environment?

2019-07-19 06:09 UTC, adejanovski commented on src/docs/content/docs/usage/sidecar_mode.md
> +   If your underlying infrastructure has limited resources, then Sidecar Mode may not be suitable for you.
That's true, and we need to work on Reaper's footprint to lighten it up as much as possible.

2019-07-19 06:09 UTC, adejanovski commented on src/docs/content/docs/usage/sidecar_mode.md
> +    You will need to setup a loadbalancer / service that ensures that all Web UI traffic from a particular client is directed to a particular Reaper process.
Sadly that's true. We need to come up with a more seamless way of handling this case.

2019-07-25 20:11 UTC, jsanda commented on src/docs/content/docs/usage/sidecar_mode.md
> + * *Kubernetes Friendly*: Sidecar mode is very easy to setup if your Cassandra Cluster is deployed using a container orchestration system, such as Kubernetes.
@adejanovski Reaper would be able to talk to Cassandra over localhost. The containers will use the same network namespace. They can also use the same volume mounts.

2019-12-06 06:11 UTC, merged

2019-12-06 06:11 UTC, adejanovski commented
Thanks a lot for the PR @wallrj, I made some adjustments and merged it (finally).