Introduce Cluster.Builder
thelastpickle/cassandra-reaper pull request #733
Opened 2019-08-02 08:48 UTC by michaelsembwever

- IStorage no longer returns Optionals against Cluster methods, if the name argument is wrong it throws an IllegalArgumentException instead,
 - Node.withClusterName(..) method and usage removed, as it was never used anywhere,
 - Rationalise ClusterFacade connection methods, simplify connection method names.
 - Remove JmxConnectionFactory.connect(node) method, only tests were using it.

2019-08-02 13:43 UTC, adejanovski requested changes
I'm not going to be dogmatic about my comments on code design, but feel that some things should be done slightly differently.
The precondition in `addOrUpdateCluster` seems like a problem though as it will prevent us from refreshing the seeds of an existing cluster.

2019-08-02 15:37 UTC, michaelsembwever commented on src/server/src/main/java/io/cassandrareaper/core/Cluster.java
> +  public int getJmxPort() {
I've intentionally avoiding the additional API of the `ClusterProperties` object. It is now only used for input into the builder.

2019-08-02 15:37 UTC, michaelsembwever commented on src/server/src/main/java/io/cassandrareaper/core/Cluster.java
> +    public Builder withJmxPort(int jmxPort) {
I've intentionally avoiding the additional API of the `ClusterProperties` object. It is now only used for input into the builder.

2019-08-02 15:41 UTC, michaelsembwever commented on src/server/src/main/java/io/cassandrareaper/resources/ClusterResource.java
> +        1 >= matchingClusters.get().count(),
it's an idiom that constants go on the left side.

those used to the idiom use it to read code faster, as the eye can tell the difference between an assignment and a equality/comparison statement when more than a single character tells them apart.

2019-08-02 15:59 UTC, michaelsembwever commented
> The precondition in addOrUpdateCluster seems like a problem though as it will prevent us from refreshing the seeds of an existing cluster.

That's not intended to be the case or consequence. Clusters certainly need to be refreshed with new seeds/nodes.

But where is this precondition you're referencing? do you mean the one actually in `updateClusterSeeds(..)`?

2019-08-02 16:03 UTC, michaelsembwever commented on src/server/src/main/java/io/cassandrareaper/resources/ClusterResource.java
> +        1 >= matchingClusters.get().count(),
> The data model should prevent that from happening anyway.

Indeed, it is a check against programmatic correctness, not against application state/behaviour.
That the db has the name as primary key is an outside concern to the code at this level. For example I was considering how to change the key to deal with multiple clusters with the same name.

I'm happy to remove the precondition though.

2019-08-05 14:44 UTC, adejanovski commented
> > The precondition in addOrUpdateCluster seems like a problem though as it will prevent us from refreshing the seeds of an existing cluster.
> 
> That's not intended to be the case or consequence. Clusters certainly need to be refreshed with new seeds/nodes.
> 
> But where is this precondition you're referencing? do you mean the one actually in `updateClusterSeeds(..)`?

I think I've been confusing with that precondition from #719 : https://github.com/thelastpickle/cassandra-reaper/pull/719/files#diff-4592ce49f2d762bf58ce1cb637352460R211

2019-08-05 14:44 UTC, adejanovski approved these changes

2019-08-05 20:44 UTC, merged