Upgrade start bootstrap 3 and new UI theme
thelastpickle/cassandra-reaper pull request #778
Opened 2019-10-25 13:29 UTC by adejanovski

Upgrades the Bootstrap admin lib we rely on from 1.0.5 to 3.3.7 and switches the color to [Superhero](https://bootswatch.com/superhero/).

![reaper-clusters](https://user-images.githubusercontent.com/5096002/67575040-f52cdd00-f73b-11e9-95c1-8643a2c7b28b.png)

![reaper-schedules](https://user-images.githubusercontent.com/5096002/67575050-fb22be00-f73b-11e9-8b02-a6540911d0ff.png)

![reaper-repair](https://user-images.githubusercontent.com/5096002/67575059-ff4edb80-f73b-11e9-8f35-2f6d0b5ac8da.png)

![reaper-snapshots](https://user-images.githubusercontent.com/5096002/67575066-037af900-f73c-11e9-9b1b-32e9df86c524.png)

![reaper-audit](https://user-images.githubusercontent.com/5096002/67575080-0c6bca80-f73c-11e9-96e5-a4737a1b5fd9.png)

![reaper-node-view](https://user-images.githubusercontent.com/5096002/67575086-0f66bb00-f73c-11e9-80aa-9f44a157b2ee.png)

2019-10-29 15:05 UTC, michaelsembwever requested changes
Build doesn't pass the RAT check.

https://circleci.com/gh/thelastpickle/cassandra-reaper/38620

2019-11-07 03:29 UTC, ossarga approved these changes
Nice work @adejanovski !! Changes look good. Have a few non-blocking comments.

2019-11-07 13:16 UTC, adejanovski commented on src/ui/app/index.js
> +  if(!currentCluster || currentCluster == "null") {
sure thing

2019-11-07 13:30 UTC, adejanovski commented on src/ui/app/style.scss
> +/*
I need this for some theming stuff. Let's keep it here for now, sorry for the mess it makes.

2019-11-07 13:50 UTC, merged