Update API documentation
thelastpickle/cassandra-reaper pull request #812
Opened 2019-12-13 17:29 UTC by atallahade

2019-12-16 09:46 UTC, adejanovski requested changes
Thanks for updating the docs @atallahade. 

Your PR removes the `force` param from the cluster deletion call. Could you bring it back before we merge?

2019-12-16 09:46 UTC, adejanovski commented on src/docs/content/docs/api.md
> +  * Expected query parameters: *None*
You might need to rebase on top of master to get the `force` param back. It's a new addition from Reaper 2.0.

2020-01-09 14:53 UTC, atallahade commented
@adejanovski I've also documented a missing endpoint.

2020-02-03 07:00 UTC, adejanovski commented
Hi @atallahade,

sorry I forgot to merge this PR. There are merge conflicts that need to be addressed, and the commits need to be squashed before I can merge it.

Thanks!

2020-02-05 09:46 UTC, merged