Added support for custom address translation
thelastpickle/cassandra-reaper pull request #833
Opened 2020-01-10 17:11 UTC by maxshel

Provide a possibility to configure simple address translator for Cassandra storage connection and and for JMX connection.
Sometimes it’s not possible for Cassandra nodes to broadcast addresses that will work for each and every client; for instance, they might broadcast private IPs because most clients are in the same network, but a particular client could be on another network and go through a router. For such cases, you can configure a custom address translator that will perform additional address translation based on configured mapping.

See Issue 832 for details (https://github.com/thelastpickle/cassandra-reaper/issues/832)

2020-02-03 07:14 UTC, adejanovski requested changes
Hi @maxshel,

thanks for sending this PR.
Could you please add some tests for `MultiIpPerNodeAddressTranslatorFactory` and rebase on top of master, fixing the merge conflicts?

Much appreciated!

2020-02-06 16:58 UTC, maxshel commented
> 
> 
> Hi @maxshel,
> 
> thanks for sending this PR.
> Could you please add some tests for `MultiIpPerNodeAddressTranslatorFactory` and rebase on top of master, fixing the merge conflicts?
> 
> Much appreciated!

Done.

2020-02-07 12:33 UTC, adejanovski requested changes
There's a typo in the documentation on the version, but the rest looks good to me.
Could you squash the commits into a single one when correcting the typo?
Then I'll merge the PR.
Thanks!

2020-02-07 12:33 UTC, adejanovski commented on src/docs/content/docs/configuration/reaper_specific.md
> +_**Since 1.1.0**_
This should be `2.1.0`  instead of `1.1.0`

2020-02-09 10:52 UTC, maxshel commented
> There's a typo in the documentation on the version, but the rest looks good to me.
> Could you squash the commits into a single one when correcting the typo?
> Then I'll merge the PR.
> Thanks!

Done

2020-02-11 14:06 UTC, adejanovski approved these changes

2020-02-11 14:07 UTC, merged

2020-02-11 14:07 UTC, adejanovski commented
Thanks a lot @maxshel 👍