Enable sidecar tests when using Elassandra
thelastpickle/cassandra-reaper pull request #885
Opened 2020-04-09 10:25 UTC by rzvoncek

2020-04-13 13:10 UTC, adejanovski requested changes
You also need to remove `--tags ~@sidecar` in `its-elassandra`:
https://github.com/thelastpickle/cassandra-reaper/pull/885/files#diff-60fe268f71ae7f8409aff40d0a3e51d8R333

2020-04-13 15:29 UTC, rzvoncek commented
Removed the other flag and amended the commit.

2020-04-17 05:54 UTC, adejanovski approved these changes

2020-04-17 05:55 UTC, adejanovski commented
:shipit:

2020-04-17 06:27 UTC, merged