Build jar package before building deb and/or rpm
thelastpickle/cassandra-reaper pull request #906
Opened 2020-04-21 17:04 UTC by simonfontana

2022-03-22 14:10 UTC, ossarga requested changes
@simonfontana thank you for submitting this patch!

A while back commit [c0a980c](https://github.com/thelastpickle/cassandra-reaper/commit/c0a980c9d0c643199c00db9de1bff939a864a944)  was made to avoid unnecessary building of the JAR files.

I agree in principle with the proposed patch. I think it needs to do more to take into account the previous issue with running the container. Specifically, as per my comments below the `prepare` target should depend on the JAR file path rather than the `package` target. In addition, the JAR file path should be a target that performs the same actions as `package`.

2022-03-22 14:10 UTC, ossarga commented on src/packaging/Makefile
>  package:
What if we also include the JAR path as a target?

```suggestion
REAPER_JAR=../server/target/cassandra-reaper-$(VERSION).jar

$(REAPER_JAR) package:
```

2022-03-22 14:10 UTC, ossarga commented on src/packaging/Makefile
> +prepare: package
Perhaps this target should depend on the JAR path? That way if the JAR exists, we just do the `prepare` steps. If the JAR file is missing we then go and build it.

```suggestion
prepare: $(REAPER_JAR)
```

We should also change the `all` target to depend on the JAR path in a similar way as well.

2022-03-26 19:26 UTC, simonfontana commented
@ossarga thanks for the review. I tried to apply your changes and verify it but after the merge with master I have some issues. They are unrelated to the change and I'm not invested enough in the project currently that I have time to sort them out. Perhaps you can help. 

```
$ docker-compose run build
Creating docker-build_build_run ... done
.........
(omitted)
.........
Hash: 64092869d3564e14cfa8
Version: webpack 4.46.0
Time: 10209ms
Built at: 03/26/2022 7:20:05 PM
 8 assets
Entrypoint index = index.js
Entrypoint schedules = schedules.js
Entrypoint repair = repair.js
Entrypoint snapshot = snapshot.js
Entrypoint segments = segments.js
Entrypoint login = login.js
Entrypoint events = events.js
Entrypoint deps = deps.js
[527] multi ./app/index.js 28 bytes {2} [built]
[528] ./app/index.js 3.68 KiB {2} [built]
[533] multi ./app/schedules.js 28 bytes {5} [built]
[534] ./app/schedules.js 3.49 KiB {5} [built]
[548] multi ./app/repair.js 28 bytes {4} [built]
[549] ./app/repair.js 3.63 KiB {4} [built]
[552] multi ./app/snapshot.js 28 bytes {7} [built]
[553] ./app/snapshot.js 3.16 KiB {7} [built]
[556] multi ./app/segments.js 28 bytes {6} [built]
[557] ./app/segments.js 2.81 KiB {6} [built]
[558] multi ./app/login.js 28 bytes {3} [built]
[559] ./app/login.js 2.52 KiB {3} [built]
[560] multi ./app/events.js 28 bytes {1} [built]
[561] ./app/events.js 3.81 KiB {1} [built]
[567] multi sb-admin-2.css bootstrap.css theme.css font-awesome.css metisMenu.css style.scss jquery react bootstrap metisMenu sb-admin-2 rxjs bootstrap-multiselect.css datatables.net-bs.css react-datepicker.css 196 bytes {0} [built]
    + 577 hidden modules

ERROR in multi sb-admin-2.css bootstrap.css theme.css font-awesome.css metisMenu.css style.scss jquery react bootstrap metisMenu sb-admin-2 rxjs bootstrap-multiselect.css datatables.net-bs.css react-datepicker.css
Module not found: Error: Can't resolve 'bootstrap-multiselect.css' in '/usr/src/app/cassandra-reaper/src/ui'
 @ multi sb-admin-2.css bootstrap.css theme.css font-awesome.css metisMenu.css style.scss jquery react bootstrap metisMenu sb-admin-2 rxjs bootstrap-multiselect.css datatables.net-bs.css react-datepicker.css deps[12]

ERROR in ./app/jsx/event-list.jsx
Module not found: Error: Can't resolve 'datatables.net' in '/usr/src/app/cassandra-reaper/src/ui/app/jsx'
 @ ./app/jsx/event-list.jsx 27:19-44
 @ ./app/jsx/event-screen.jsx
 @ ./app/events.js
 @ multi ./app/events.js

ERROR in multi sb-admin-2.css bootstrap.css theme.css font-awesome.css metisMenu.css style.scss jquery react bootstrap metisMenu sb-admin-2 rxjs bootstrap-multiselect.css datatables.net-bs.css react-datepicker.css
Module not found: Error: Can't resolve 'datatables.net-bs.css' in '/usr/src/app/cassandra-reaper/src/ui'
 @ multi sb-admin-2.css bootstrap.css theme.css font-awesome.css metisMenu.css style.scss jquery react bootstrap metisMenu sb-admin-2 rxjs bootstrap-multiselect.css datatables.net-bs.css react-datepicker.css deps[13]

ERROR in ./app/jsx/event-list.jsx
Module not found: Error: Can't resolve 'datatables.net-bs.js' in '/usr/src/app/cassandra-reaper/src/ui/app/jsx'
 @ ./app/jsx/event-list.jsx 31:23-54
 @ ./app/jsx/event-screen.jsx
 @ ./app/events.js
 @ multi ./app/events.js

ERROR in multi sb-admin-2.css bootstrap.css theme.css font-awesome.css metisMenu.css style.scss jquery react bootstrap metisMenu sb-admin-2 rxjs bootstrap-multiselect.css datatables.net-bs.css react-datepicker.css
Module not found: Error: Can't resolve 'font-awesome.css' in '/usr/src/app/cassandra-reaper/src/ui'
 @ multi sb-admin-2.css bootstrap.css theme.css font-awesome.css metisMenu.css style.scss jquery react bootstrap metisMenu sb-admin-2 rxjs bootstrap-multiselect.css datatables.net-bs.css react-datepicker.css deps[3]

ERROR in multi sb-admin-2.css bootstrap.css theme.css font-awesome.css metisMenu.css style.scss jquery react bootstrap metisMenu sb-admin-2 rxjs bootstrap-multiselect.css datatables.net-bs.css react-datepicker.css
Module not found: Error: Can't resolve 'jquery' in '/usr/src/app/cassandra-reaper/src/ui'
 @ multi sb-admin-2.css bootstrap.css theme.css font-awesome.css metisMenu.css style.scss jquery react bootstrap metisMenu sb-admin-2 rxjs bootstrap-multiselect.css datatables.net-bs.css react-datepicker.css deps[6]

ERROR in ./app/segments.js
Module not found: Error: Can't resolve 'jquery' in '/usr/src/app/cassandra-reaper/src/ui/app'
 @ ./app/segments.js 3:14-31
 @ multi ./app/segments.js

ERROR in ./app/login.js
Module not found: Error: Can't resolve 'jquery' in '/usr/src/app/cassandra-reaper/src/ui/app'
 @ ./app/login.js 3:14-31
 @ multi ./app/login.js

ERROR in ./app/schedules.js
Module not found: Error: Can't resolve 'jquery' in '/usr/src/app/cassandra-reaper/src/ui/app'
 @ ./app/schedules.js 3:14-31
 @ multi ./app/schedules.js

ERROR in ./app/repair.js
Module not found: Error: Can't resolve 'jquery' in '/usr/src/app/cassandra-reaper/src/ui/app'
 @ ./app/repair.js 3:14-31
 @ multi ./app/repair.js

ERROR in ./app/events.js
Module not found: Error: Can't resolve 'jquery' in '/usr/src/app/cassandra-reaper/src/ui/app'
 @ ./app/events.js 3:14-31
 @ multi ./app/events.js

ERROR in ./app/observable.js
Module not found: Error: Can't resolve 'jquery' in '/usr/src/app/cassandra-reaper/src/ui/app'
 @ ./app/observable.js 12:14-31
 @ ./app/index.js
 @ multi ./app/index.js

ERROR in ./app/index.js
Module not found: Error: Can't resolve 'jquery' in '/usr/src/app/cassandra-reaper/src/ui/app'
 @ ./app/index.js 3:14-31
 @ multi ./app/index.js

ERROR in ./app/snapshot.js
Module not found: Error: Can't resolve 'jquery' in '/usr/src/app/cassandra-reaper/src/ui/app'
 @ ./app/snapshot.js 3:14-31
 @ multi ./app/snapshot.js

ERROR in ./app/jsx/cluster-list.jsx
Module not found: Error: Can't resolve 'jquery' in '/usr/src/app/cassandra-reaper/src/ui/app/jsx'
 @ ./app/jsx/cluster-list.jsx 37:14-31
 @ ./app/jsx/cluster-screen.jsx
 @ ./app/index.js
 @ multi ./app/index.js

ERROR in ./app/jsx/dropped-messages.jsx
Module not found: Error: Can't resolve 'jquery' in '/usr/src/app/cassandra-reaper/src/ui/app/jsx'
 @ ./app/jsx/dropped-messages.jsx 25:14-31
 @ ./app/jsx/node-status.jsx
 @ ./app/jsx/cluster-list.jsx
 @ ./app/jsx/cluster-screen.jsx
 @ ./app/index.js
 @ multi ./app/index.js

ERROR in ./app/jsx/snapshot.jsx
Module not found: Error: Can't resolve 'jquery' in '/usr/src/app/cassandra-reaper/src/ui/app/jsx'
 @ ./app/jsx/snapshot.jsx 29:14-31
 @ ./app/jsx/node-status.jsx
 @ ./app/jsx/cluster-list.jsx
 @ ./app/jsx/cluster-screen.jsx
 @ ./app/index.js
 @ multi ./app/index.js

ERROR in ./app/jsx/event-screen.jsx
Module not found: Error: Can't resolve 'jquery' in '/usr/src/app/cassandra-reaper/src/ui/app/jsx'
 @ ./app/jsx/event-screen.jsx 1:0-17
 @ ./app/events.js
 @ multi ./app/events.js

ERROR in ./app/jsx/snapshot-screen.jsx
Module not found: Error: Can't resolve 'jquery' in '/usr/src/app/cassandra-reaper/src/ui/app/jsx'
 @ ./app/jsx/snapshot-screen.jsx 1:0-17
 @ ./app/snapshot.js
 @ multi ./app/snapshot.js

ERROR in ./app/jsx/segment-list.jsx
Module not found: Error: Can't resolve 'jquery' in '/usr/src/app/cassandra-reaper/src/ui/app/jsx'
 @ ./app/jsx/segment-list.jsx 33:14-31
 @ ./app/segments.js
 @ multi ./app/segments.js

ERROR in ./app/jsx/client-request-latency.jsx
Module not found: Error: Can't resolve 'jquery' in '/usr/src/app/cassandra-reaper/src/ui/app/jsx'
 @ ./app/jsx/client-request-latency.jsx 33:14-31
 @ ./app/jsx/node-status.jsx
 @ ./app/jsx/cluster-list.jsx
 @ ./app/jsx/cluster-screen.jsx
 @ ./app/index.js
 @ multi ./app/index.js

ERROR in ./app/jsx/cluster-selection.jsx
Module not found: Error: Can't resolve 'jquery' in '/usr/src/app/cassandra-reaper/src/ui/app/jsx'
 @ ./app/jsx/cluster-selection.jsx 1:0-17
 @ ./app/jsx/event-screen.jsx
 @ ./app/events.js
 @ multi ./app/events.js

ERROR in ./app/jsx/event-list.jsx
Module not found: Error: Can't resolve 'jquery' in '/usr/src/app/cassandra-reaper/src/ui/app/jsx'
 @ ./app/jsx/event-list.jsx 19:14-31
 @ ./app/jsx/event-scree [...]

2022-11-25 10:55 UTC, ossarga commented
@adejanovski, I have a [branch](https://github.com/thelastpickle/cassandra-reaper/compare/master...anthony/ISSUE-890/build_jar_when_creating_packages) with changes on it that incorporates @simonfontana's original fix and addresses the compile issue that was encountered.

Should we close this pull request and I'll open a new one with all the changes?

2022-11-28 09:00 UTC, adejanovski commented
> Should we close this pull request and I'll open a new one with all the changes?

@ossarga, yes, works for me.

2023-06-19 13:53 UTC, closed without merging