add REAPER_CASS_ADDRESS_TRANSLATOR_MAPPING env var for multiIpPerNode…
thelastpickle/cassandra-reaper pull request #986
Opened 2020-11-04 17:26 UTC by mzaghab

add a new env var `REAPER_CASS_ADDRESS_TRANSLATOR_MAPPING ` that gives the possiblity to specify the mapping ip for the `multiIpPerNode` address translator type
example env:
```
 
REAPER_CASS_ADDRESS_TRANSLATOR_TYPE=multiIpPerNode REAPER_CASS_ADDRESS_TRANSLATOR_MAPPING=host1:ip1,host2:ip2
```
will generate the below config bloc at the container startup file '/etc/cassandra-reaper.yml'  :
```
 addressTranslator:
    type: multiIpPerNode
    ipTranslations:
    - from: "host1"
      to: "ip1"
    - from: "host2"
      to: "ip2"
```

2020-11-05 06:13 UTC, adejanovski requested changes
Hi @mzaghab,

thanks for pushing this PR!
I have two small requests:

- Could you add some documentation about these new settings [in the docker variables section](https://github.com/thelastpickle/cassandra-reaper/blob/master/src/docs/content/docs/configuration/docker_vars.md)?
- Could you squash your commits into a single one and force push once that is done?

That would be great!

2020-11-05 08:25 UTC, mzaghab commented
hi @adejanovski, 
documentation updated and the 2 commits was squashed once.
regards

2020-11-05 08:32 UTC, adejanovski commented
Thanks @mzaghab.

For the documentation, I was hoping you could create a specific section in the `docker_vars.md` page with the examples you provided in the description of this PR.
This will help folks figure out how to set those variables and understand how it will translate into the yaml.
It's mostly a copy paste of the PR description without `add a new env var` at the beginning.

2020-11-05 10:16 UTC, mzaghab commented
hi @adejanovski i created a new section for the address translator mapping
<img width="1268" alt="Capture d’écran 2020-11-05 à 11 14 25" src="https://user-images.githubusercontent.com/1429079/98227988-47602b00-1f58-11eb-975b-388cf60af263.png">

2020-11-06 09:02 UTC, adejanovski approved these changes
That's perfect, thanks!

2020-11-06 09:02 UTC, merged